# ServerTools - Reece#3370
# -----------------------------------------------------------------
# DEFAULT PERMISSIONS
# hunger.bypass         nofalldamage.use        anticraft.bypass
# chatcooldown.bypass   ctag.use                Chatcolor.COLOR (.*)
#                                               Chatcolor.codes ((& color codes)
#
# LANGUAGES: "en and "de"
#
# Staff Related
# mutechat.use              mutechat.bypass         anticraft.admin
# clearchat.use             chatcooldown.admin      announce.use
# colon.use                 Freeze.use              
# whitelist.bypass          staffafk.use            cmdalias.bypass
# changeslots.use           guess.admin             donation.use
# tools.tpall               countdown.use           tools.rename
# visibility.bypass         poll.use                tools.rename.lore
# visibility.staff
# tools.clearlag            giveall.use             hologram.admin
# report.notify             tools.speed.walk        tools.speed.fly       tools.scheduledtask.admin
# -----------------------------------------------------------------
# worlds are case sensitive

LoadWithTimings: true
Language: en

# Can be used within servertools with %NAME%.
PluginVariables:
  STORE: https://store.WEBSITE.co
  DISCORD: https://discord.gg/INVITE
  RULES: https://WEBSITE.co/rules
  WEBSITE: https://WEBSITE.co
  SERVERNAME: '&A&lCRAFT&f&lNETWORK'
  SERVER: Hub-01
  SUPPORT: discord.com/invite/SUPPORTSERVER


FeaturesGUI:
  Enabled: false

Disabled:
  DisableCropTrample:
    Enabled: false
  DisableGrassDecay:
    Enabled: true
  DisableBookWriting:
    Enabled: true
  DisableDragonEggTP:
    Enabled: true
  DisableVillagerTrading:
    Enabled: true
    Permission: villagertrading.use
    Message: '&cVillager trading is disabled &7&o((%perm%))!'
  DisableCactusDamage:
    Enabled: true
  DisableCaneTowers:
    Enabled: true
  DisableJockeySpawning:
    Enabled: true
  DisableBlazeDrowning:
    Enabled: true
  DisableJoinLeaveMsg:
    Enabled: true
  DisableDisconnectSpamKick:
    Enabled: true
  DisableHunger:
    Enabled: true
    Permission: ''
  DisableFallDamage:
    Enabled: true
    Permission: ''
  DisableEndermanTP:
    Enabled: true
  DisableWitherBlockBreak:
    Enabled: true
  DisableGolemPoppies:
    Enabled: true
  DisableStackablePotions:
    Enabled: true
  DisablePhantomSpawn:
    Enabled: true
  DisableIceMelt:
    Enabled: true
  DisableBlockBreaking:
    Enabled: true
    Permission: tools.breakblock.bypass
  DisableBlockPlacement:
    Enabled: true
    Permission: tools.blockplace.bypass

  DisableItemBurn:
    Enabled: true
    reasons:
    - 'lava'
    - 'fire'
    - 'fire_tick'
    - 'BLOCK_EXPLOSION'
    - 'ENTITY_EXPLOSION'
  DisableLeaveDecay:
    Enabled: true
    WorldsToDisable:
    - 'world'
  DisableWeather:
    Enabled: true
    worlds:
    - 'world'
  DisableTimeChange:
    Enabled: true
    DayInAllWorlds: true
    SecondSync: 60
    DayWorlds:
    - 'world'
    NightWorlds:
    - 'None'
  DisableEntityThrowing:
    Enabled: true
    Items:
    - 'EYE_OF_ENDER'
    - 'EGG'
  DisableWaterBreakingRedstone:
    Enabled: true
    items:
    - 'REDSTONE'
    - 'DIODE'
    - 'DIODE_BLOCK_ON'
    - 'DIODE_BLOCK_OFF'
    - 'REDSTONE_WIRE'
    - 'REDSTONE_TORCH_ON'
    - 'REDSTONE_TORCH_OFF'
    - 'REDSTONE_COMPARATOR'
    - 'REDSTONE_COMPARATOR_OFF'
    - 'REDSTONE_COMPARATOR_ON'

  DisableMobAI:
    Enabled: true
    worldsToDisable:
    - 'world'

  DisableWorldGuardGlitchBuilding:
    # bypass perm: blockglitchplace.bypass
    Enabled: false


Core:
  Ping:
    Enabled: false
  InvSee:
    Enabled: false
    Permission: essentials.invsee
    ModifyOthers: essentials.invsee.modify
    StaffNoModify: essentials.invsee.preventmodification
  God:
    Enabled: false
    Permission: essentials.god
  Trash:
    Enabled: true
  Nickname:
    Enabled: false
    Permission: nickname.use
    prefix: '~'
    prefixBypass: nickname.prefixbypass
  Top:
    Enabled: true
    Permission: essentials.top
  Enderchest:
    Enabled: false
    Permission: essentials.enderchest
    ViewOthers: essentials.enderchest.others
    ModifyOthers: essentials.enderchest.modify
  Repair:
    Enabled: false
    Single:
      Permission: essentials.repair
      Cost: 1500.0
    All:
      Permission: essentials.repair.all
      Cost: 15000.0
  Compass:
    Enabled: false
    Permission: essentials.compass
  Extinguish:
    Enabled: false
    Permission: essentials.ext
    StaffPermission: essentials.ext.others
  Hat:
    Enabled: true
    Permission: essentials.hat
  Workbench:
    Enabled: true
    Permission: essentials.workbench
  Fly:
    Enabled: true
    Permission: essentials.fly
  Enchant:
    Enabled: true
    Permission: essentials.enchant
  ClearInv:
    Enabled: true
    Permission: essentials.clearinventory
  Broadcast:
    Enabled: true
    Permission: essentials.broadcast
  AdminChat:
    Enabled: true
    Permission: tools.adminchat
  Messaging:
    Enabled: true
    Permissions:
      Message: essentials.message
      Reply: essentials.reply
      SocialSpy: essentials.socialspy
      ToggleMSG: essentials.togglemsg
      DisableMessaging: chat.disablemessaging
      StaffBypass: staff.bypassdisabledmsg
    Formats:
      Send: '&7(To &A%name%&7) &A%msg%'
      From: '&7(From &A%name%&7) &A%msg%'
    Sound:
      Enabled: true
      Sound: BLOCK_NOTE_BLOCK_PLING
  Gamemode:
    Enabled: true
    Permissions:
      Creative: essentials.gamemode.creative
      Survival: essentials.gamemode.survival
      Spectator: essentials.gamemode.spectator
      Adventure: essentials.gamemode.Adventure
  Heal:
    Enabled: true
    Permissions:
      Heal: essentials.heal
      HealOthers: essentials.heal.others
      Feed: essentials.feed
  Teleport:
    Enabled: true
    Permissions:
      TP: essentials.tp
      TPA: essentials.tpa
      TPHere: essentials.tphere
  Spawn:
    Enabled: true
    CommandPermission: spawn.use
    Permission: spawn.admin
    onJoinInstantly: false
    spawnFirstUniqueJoinOnly: true
    teleportWhenInVoid:
      Enabled: true
      disabledWorlds:
      - 'world_nether'
      message: '&4&l[!] &4OOPS! &cYou fell into the void. Sent to spawn.'

  Warps:
    Enabled: true
    DeleteWarpPerm: tools.delwarp
    SetWarpPerm: tools.setwarp
    ViewWarpPerm: tools.viewwarp
    WarpOtherPlayToWarpPerm: tools.warpother

Commands:
  Countdown:
    Enabled: false
  AltTP:
    Enabled: false
  ChangeSlots:
    Enabled: true
    Permission: changeslots.use
    AnnounceFullToPermissionedUsers: true
  ChatPoll:
    Enabled: false
  GiveAll:
    Enabled: false
  ChatNumberGuess:
    Enabled: false
    command: guess
    AdminPerm: guess.admin
  DailyRewards:
    Enabled: false
    rewards:
    - 'crate give P Rare 1 %player%'
  reclaim:
    Enabled: false
    BeginAtIndex: 6
    permissions:
      group_dragon:
      - 'bundle give %player% DragonReclaim 1'
      group_king:
      - 'bundle give %player% KingReclaim 1'
      group_wizard:
      - 'bundle give %player% WizardReclaim 1'
      group_goblin:
      - 'bundle give %player% GoblinReclaim 1'
 
  Speed:
    Enabled: true
    FlyPermission: tools.speed.fly
    WalkPermission: tools.speed.walk
 
  StaffList:
    Enabled: true
    groups:
      owner: ' &8&l<&d&lOWNER&8&l> &f» &d'
      manager: ' &8&l<&6&lMANAGER&8&l> &f» &6'
      developer: ' &8&l<&b&lDEVELOPER&8&l> &f» &b'
      admin: ' &8&l<&c&lADMIN&8&l> &f» &c'
      srmoderator: ' &8&l<&9&lSRMOD&8&l> &f» &9'
      moderator: ' &8&l<&e&lMOD&8&l> &f» &e'
      helper: ' &8&l<&a&lHELPER&8&l> &f» &a'
      builder: ' &8&l<&3&lBUILDER&8&l> &f» &3'
      staffafk: ' &8&l<&7&lAFK&8&l> &f» &7'
        
 
Chat:
  CustomDeathMessages:
    Enabled: true
    message: '&7&o[-] %message%'
    #Toggle in game with /toggledeath
      
  ChatCooldown:
    Enabled: true
    BypassCooldown: chatcooldown.bypass
    CommandPermission: chatcooldown.admin
    SecondsCooldown: 5
    Message: '&6&l[!] &eYou must wait &6&n%timeleft%s&e before you may chat again.'
    
  ChatFormat:
    Enabled: true
    EnabledPAPIinMessages: true
    ChatColorPerm: chatcolor.codes
    PrefixOffset: 0
    format: '{prefix}{name}{suffix} &7» &f{message}'
   
  Tags:
    Enabled: true
    CustomTagPerm: ctag.use
    CustomMaxLength: 20
    CustomTagFormat: '&8&l<%tag%&8&l>'
    selected: '&e&l[!] &eYou have selected &r%tag% &eas your new tag!'
    removed: '&c&l[!] &cYou have removed your &4current&c tag!'
    giveTagCmd: lp user %name% permission set tags.%tag% true server=skyblock_emc
    
  ChatColor:
    Enabled: true
    RainbowColors:
    - '&f'
    - '&e'
    - '&6'
    - '&b'
    - '&2'
    - '&4'
    - '&7'
  NameColor:
    Enabled: true
    
  ChatEmoji:
    Enabled: true
    permission: ''
    Emojis:
      <3: ♡
      :flip:: (╯°□°)╯︵ ┻━┻
      :serious:: (ಠ_ಠ)
   
Events:
  AntiCraft:
    Enabled: false
    AdminPerm: anticraft.admin
    Bypass: anticraft.bypass
    MSG: '&c&l[!] &cYou do not have permission to craft &e%item%&c.'
    
  StackUnstackables:
    Enabled: false
    items:
    - 'SADDLE'
    - 'SHEARS'
    - 'EGG'
    - 'IRON_BARDING'
    - 'GOLD_BARDING'
    - 'DIAMOND_BARDING'
    
  WorldEffects:
    Enabled: true
    # https://helpch.at/docs/1.12.2/index.html?org/bukkit/potion/PotionEffectType.html
    worlds:
    - 'world:NIGHT_VISION:1'
    
  ChatJoinMOTD:
    Enabled: true
    MOTD:
    - ''
    - '&8&l>&7&m-------------&r %SERVERNAME% &7&m------------&8&l<'
    - ''
    - '&2&l▎ &A&lSERVER &f%SERVER%'
    - ''
    - '&2&l▎ &A&lSTORE &f%STORE%'
    - '&2&l▎ &A&lDISCORD &f%DISCORD%'
    - ''
    - '&7&o(( Currently &A&o%server_online% &7&oplayer(s) are playing ))'
    - ''
    - '&8&l>&7&m----------------------------------------&8&l<'
    
  NoBedExplosionInNether:
    Enabled: true
    
  # https://helpch.at/docs/1.12.2/org/bukkit/Material.html  
  Launchpads:
    Enabled: true
    BlockType: EMERALD_BLOCK
    PlateType: STONE_PLATE
    LaunchPower: 1
    RunnableTicksperCheck: 7

Moderation:
  MuteChat:
    Enabled: true
    Permission:
      Use: mutechat.use
      Bypass: mutechat.bypass
    Messages:
      Enabled: '&a&l[!] &2&n%player%&a has unmuted the chat!'
      Disable: '&c&l[!] &4&n%player%&c has muted the chat!'
    
  CommandSpy:
    Enabled: false
    permission: commandspy.use
    ignored_commands:
    - 'msg'
    
  CommandProtect:
    Enabled: true
    
  ClearChat:
    Enabled: true
    Permission: clearchat.use
    Messages:
      lines: 100
      msg: '&e&l[!] &6&n%player%&e has cleared the chat!'
      
  NoColonInCommands:
    Enabled: true
    BypassPerm: colon.use
    
  Freeze:
    Enabled: false
    Permission: Freeze.use
    Message:
    - '&6&l[!]&e You have been frozen. &7&o(( Do not log out ))'
    - '&dYou have &f2 &dminutes to join the discord:'
    - '&f - &d%SUPPORT%'
    
  WhitelistBypass:
    Enabled: true
    DisableWhitelistCMDInGame: true
    Permission: whitelist.bypass
    Message: '&c&n%player%&c, you are not whitelisted on this server!'

  TPAll:
    Enabled: true
 
  Report:
    Enabled: false
    Cooldown: 30
    CooldownMSG: '&4[!] &cYou can not make another report for %timeleft% seconds!'
    ReportSuccess: '&c%reporter%&f reported &c%offender% &ffor &c%reason%'
 
  StaffAFK:
    Enabled: false
    StaffAFKGroup: staffafk
    Permission: staffafk.use
    StaffGroups:
    - 'owner'
    - 'admin'
    - 'srmod'
    - 'mod'
    - 'helper'
    GiveAFK:
    - 'lp user %player% parent add %StaffAFKGroupName% server=global'
    - 'lp user %player% parent remove %UsersPrimaryGroup% server=global'
    RemoveAFK:
    - 'lp user %player% parent add %PlayerConfigPrimarygroup% server=global'
    - 'lp user %player% parent remove %StaffAFKGroupName% server=global'
    

Cooldowns:
  EnderPearlCooldown:
    Enabled: false
    Seconds: 15
    Message: '&6&l[!] &eYou must wait &6&n%timeleft%s&e before you may throw this again.'
  GoldenAppleCooldown:
    Enabled: false
    Seconds: 15
    Message: '&6&l[!] &eYou must wait &6&n%timeleft%s&e before you may eat another.'
    StartCooldownMSG: '&7&o(( GOLDEN APPLE EATEN! %seconds% second cooldown initiated ))'
  GodAppleCooldown:
    Enabled: false
    Seconds: 45
    Message: '&6&l[!] &eYou must wait &6&n%timeleft%s&e before you may eat another.'
    StartCooldownMSG: '&7&o(( GOD APPLE EATEN! %seconds% second cooldown initiated ))'
    


Misc:
  Tools:
    Permission: toolscmd.admin
    
  Withdraw:
    # Console: "/withdraw AMOUNT player"
    Enabled: false
    
  Rename:
    Enabled: true
    permission: tools.rename
    lorePermission: tools.rename.lore
    disabledRename:
    - 'AIR'
    - 'EXP_BOTTLE'
    - 'BEACON'

  ClearLag:
    Enabled: false
    AutoClearItems:
      Enabled: true
      ClearMobs: true
      ClearDelay: 900
      ClearSoonMSG: '&f&l[LAG] &cClearing all entities in %seconds% seconds'
      ClearedMSG: '&f&l[LAG] &cAll entities have been cleared...'

  ThreeHitGlitch:
    Enabled: false

  OnJoinCommands:
    Enabled: false
    FirstUniqueJoin:
      Enabled: false
      CMDS:
      - 'skyhoes give 1 %player%'
    PlayerRunCommands:
      Enabled: false
      CMDS:
      - 'pg join'

  Visibility:
    Enabled: true
    bypassPerm: visibility.bypass
    
  BucketStacker:
    Enabled: false
    worldguard: false
    superiorskyblock: false
    
  Holograms:
    Enabled: true
    
  ScheduledTask:
    Enabled: false
    Debug: false
    Permission: tools.scheduledtask.admin
  
  CMDAliases:
    Enabled: true
    Permission: cmdalias.bypass
    cmds:
      colors: essentials:info colors
      menu: ultracosmetics menu main
      warzone: warp pvp
      cane: tokens
      croptop: croptop cane
      votetop: superbvote top
      v: essentials:vanish
      ce: enchanter
      cactus: cactusshop
      mutechat: servertools:mutechat
      clearchat: servertools:clearchat
      vote: vote sites
    disabled:
    - 'pl'
    - 'plugins'
    - '?'
    - 'version'
    - 'debug'
    - 'about'
    - 'ver'
    - 'esell'
    - 'essentials:sell'
    - 'essentials:esell'
    - 'bukkit:help'
    - 'bukkit:pl'
    - 'bukkit:?'
    - 'bukkit:about'
    - 'bukkit:plugins'
    - 'bukkit:timings'
    - 'bukkit:ver'
    - 'bukkit:version'
    - 'minecraft:me'
    
    # command%timeToWaitTillExectute
    preCooldownCommands:
      stopIfMoved: false
      warzone:
      - 'spawn%5'
      - 'tpyes%5'
      - 'tpaccept%5'
      - 'tpa%5'
      - 'warp pvp%5'
    
    disabledWorlds:
      spawn:
      - 'top'
      - 'etop'
      - 'sethome'
      - 'esethome'
      Warzone:
      - 'top'
      - 'etop'
      - 'sethome'
      - 'esethome'
      - 'pv'
      - 'playervaults'
      - 'playervault'
      - 'is accept'
      - 'is join'
      - 'printer'
      - 'kit'
      - 'ekit'
      - 'ekits'
      - 'skit'
      - 'ah'
      - 'pv'
      - 'ec'
      - 'vault'
      - 'enderchest'
      - 'eec'
      - 'eechest'
      - 'eendersee'
      - 'endersee'
      - 'reclaim'
      - 'skits'

Bungee:
  BungeeServerCMD:
    Enabled: false
    command: join
    Aliases:
      ogskyblock: skyblock_emc

AutoBroadcast:
  Enabled: true
   
Donation:
  Enabled: true
  Permission: donation.use
  Message:
  - ''
  - '&d✧&f✧&5✧ &d&lNEW DONATION &5✧&f✧&d✧'
  - '&7&o"We currently have a &f&o50% OFF SALE&7&o."'
  - ''
  - '&5* &f%player% &djust purchased the'
  - '&f%package% &dpackage! &a&nGG!'
  - ''
  - '&7&o(( %STORE% &7&o))'
  - ''
  
FancyAnnounce:
  # You can use the %player% variable on any line
  Enabled: true
  Permission: announce.use
  Groups:
    bosses:
      ArgumentsSyntax: <BossName> <Location>
      CenterMessage: true
      Message:
      - '&d&m-----------------------------------------------------'
      - ''
      - '&d✧&f✧&5✧ &d&lBoss Spawn &5✧&f✧&d✧'
      - ''
      - '&5* &dA &f%arg-1% &djust Spawned at'
      - '&f%arg-2%'
      - ''
      - '&d&m-----------------------------------------------------'


ServerInfoCMDS:
  Enabled: true
      
ShopWorkAround:
  # This patch gets the name of the SHOP plugin you use (( ex. ShopGUIPlus ))
  # It then gets the shopmenu name, and items in the shop's names (( ex. "&4&lSpawners" ))
  # then on click of this item in this inv, it will cancel the event and instead make the player
  #    run what ever command you want
  #
  # MenuNameInConfig = the location in YAML format of the shop menu name. It might be "Shop.InvName", where
  # the "." = a new line with 2 spaces.
  Enabled: false
  DEBUG: false
  plugin: ShopGUIPlus
  MenuNameInConfig: shopMenuName
  KeysofItemsInConfig: shopMenuItems
  NameOfItem: shopMenuItems.%key%.item.name
  RemappedClicks:
    1:
      name: '&c&lSpawners'
      CloseInvBeforeCommand: true
      MakePlayerSayCommand: true
      command: spawnershop
      
Vouchers:
  Enabled: false
  Options:
    RedeemMessage: '&a&l[+]&a You redeemed the %voucher% &7(%voucherid%)'
    Glowing: false
